IN_ROWS = 192
IN_COLS = 192
PRETRAINED_NUM_OF_CHANNELS = 4
FINE_TUNE_NUM_OF_CHANNELS = 1
NUM_OF_CLASSES = 1
STARTING_LAERNING_RATE = 1e-4
END_LEARNING_RATE = 1e-8
MAX_NUM_OF_EPOCHS = 2000  # just a huge number. The actual training should not be limited by this value
MAX_NUM_OF_EPOCHS_FIRST_LAYER_ONLY = 5
VAL_RATIO = 0.2
PATIENCE = 2
DACEY_FACTOR = 0.7
BATCH_SIZE = 32
MAX_BIT = 65535  # maximum gray level in landsat 8 images
GLOBAL_PATH = '/opt/DL_project/'

GEN_TRAIN = "gen_train"
GEN_VAL = "gen_val"
GEN_TEST = "gen_test"